name: iOS Test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace KoreanMasterCMSPreBuild.xcodeproj
          -scheme KoreanMasterCMSPreBuild -destination 'platform=iOS Simulator,name=iPhone
          15,OS=17.2'
