name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build and Test
        run: |
          xcodebuild -workspace KoreanMasterCMSPreBuild.xcworkspace -scheme KoreanMasterCMSPreBuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' build test
